# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-06 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numerique', '0002_logiciel_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logiciel',
            name='nomFichier',
            field=models.CharField(max_length=200),
        ),
    ]
